Implement try..catch in props of type function
selsa-inube/inubekit-select pull request #3
Opened 2024-03-08 20:45 UTC by cmarin001

In a strategic move to bolster the application's stability and user experience, this pull request introduces a comprehensive enhancement across our UI components involving the implementation of try..catch blocks within all function-type props. This update aims to elevate error handling mechanisms, ensuring that exceptions within these functions are gracefully managed and do not adversely affect the overall application performance or user interaction.

2024-03-08 21:51 UTC, JanuarAsprilla approved these changes

2024-03-08 22:49 UTC, wfercanas requested changes

2024-03-08 22:49 UTC, wfercanas commented on src/Select/index.tsx
>      setDisplayList(false);
If we leave this statement here, the list won't hide ever again if an error is thrown.
Let's first setDisplayList(false) and then use the `try..catch`.

2024-03-08 22:49 UTC, wfercanas commented on src/Select/index.tsx
>      setDisplayList(!displayList);
Here we have the same issue as in `onChange`. Leave the `try..catch` to the end

2024-03-11 16:22 UTC, cmarin001 commented on src/Select/index.tsx
>      setDisplayList(false);
solved

2024-03-11 16:22 UTC, cmarin001 commented on src/Select/index.tsx
>      setDisplayList(!displayList);
solved

2024-03-11 17:38 UTC, JanuarAsprilla approved these changes

2024-03-11 23:40 UTC, wfercanas approved these changes

2024-03-11 23:40 UTC, merged